# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-19 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aleady',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='YuanDongCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, default='11111111', max_length=100, unique=True, verbose_name='用户编号')),
                ('nickname', models.CharField(max_length=200, verbose_name='用户名')),
                ('vin_number', models.CharField(max_length=100, verbose_name='VIN')),
                ('mobile', models.CharField(max_length=100, null=True, verbose_name='手机')),
                ('plate_number', models.CharField(max_length=100, null=True, verbose_name='车牌号')),
                ('engine_sn', models.CharField(max_length=40, null=True, verbose_name='发动机号')),
                ('mileage', models.CharField(default='0', max_length=100, verbose_name='出厂公里')),
                ('create_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='建档日期')),
                ('assure_company', models.CharField(blank=True, max_length=100, null=True, verbose_name='保险公司')),
                ('update', models.BooleanField(default=False, verbose_name='更新推送')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='更新时间')),
                ('push', models.BooleanField(default=False, verbose_name='车辆推送状态')),
                ('error', models.BooleanField(default=False, verbose_name='车辆推送结果')),
            ],
        ),
        migrations.CreateModel(
            name='YuanDongOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=100, verbose_name='用户编号')),
                ('shop_name', models.CharField(default='上海一汽丰田元东', max_length=100)),
                ('server_sa', models.CharField(blank=True, max_length=100, verbose_name='服务专员')),
                ('order_id', models.CharField(blank=True, max_length=100, verbose_name='订单编号')),
                ('input_time', models.CharField(blank=True, max_length=100, verbose_name='订单日期')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='客户姓名')),
                ('mobile', models.CharField(blank=True, max_length=100, verbose_name='客户手机号')),
                ('plate_number', models.CharField(blank=True, max_length=100, verbose_name='车牌号')),
                ('vin_number', models.CharField(blank=True, max_length=100, verbose_name='vin')),
                ('money', models.CharField(blank=True, max_length=30, verbose_name='费用')),
                ('repair_type', models.CharField(blank=True, max_length=30, verbose_name='维修类型')),
                ('item', models.TextField(blank=True, verbose_name='维修项目')),
                ('push', models.BooleanField(default=False, verbose_name='推送状态')),
                ('error', models.BooleanField(default=False, verbose_name='推送结果')),
            ],
            options={
                'verbose_name': '维修工单',
                'verbose_name_plural': '维修工单',
            },
        ),
        migrations.CreateModel(
            name='YuanDongUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='用户编号')),
                ('nickname', models.CharField(max_length=200, verbose_name='用户名')),
                ('owner_property', models.CharField(default='个人', max_length=20, verbose_name='用户属性')),
                ('subordinate_departments', models.CharField(blank=True, max_length=200, verbose_name='隶属部门')),
                ('mobile', models.CharField(blank=True, max_length=100, verbose_name='手机')),
                ('IDcard', models.CharField(blank=True, max_length=100, verbose_name='身份证')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='地址')),
                ('update', models.BooleanField(default=False, verbose_name='更新推送')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='建档日期')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='更新时间')),
                ('userpush', models.BooleanField(default=False, verbose_name='用户推送状态')),
                ('carpush', models.BooleanField(default=False, verbose_name='车辆推送状态')),
                ('usererror', models.BooleanField(default=False, verbose_name='用户推送结果')),
                ('carerror', models.BooleanField(default=False, verbose_name='车辆推送结果')),
            ],
        ),
    ]
